// Code generated by options-gen v0.54.0. DO NOT EDIT.

package keycloakclient

type OptOptionsSetter func(o *Options)

func NewOptions(
	basePath string,
	realm string,
	clientID string,
	clientSecret string,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.basePath = basePath
	o.realm = realm
	o.clientID = clientID
	o.clientSecret = clientSecret

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithDebugMode(opt bool) OptOptionsSetter {
	return func(o *Options) { o.debugMode = opt }
}

func (o *Options) Validate() error {
	return nil
}
